package pojo;
// Generated Apr 5, 2018 8:19:09 PM by Hibernate Tools 4.3.1



/**
 * SinhVien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {


     private String maSinhVien;
     private String hoTen;
     private SvAccount idsvaccount;

    public SinhVien() {
    }

	
    public SinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public SinhVien(String maSinhVien, String hoTen, SvAccount idsvaccount) {
       this.maSinhVien = maSinhVien;
       this.hoTen = hoTen;
       this.idsvaccount = idsvaccount;
    }
   
    public String getMaSinhVien() {
        return this.maSinhVien;
    }
    
    public void setMaSinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public SvAccount getIdsvaccount() {
        return this.idsvaccount;
    }
    
    public void setIdsvaccount(SvAccount idsvaccount) {
        this.idsvaccount = idsvaccount;
    }




}


