package pojo;
// Generated Apr 2, 2018 11:25:58 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Sinhvien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {


     private String maSinhVien;
     private String tenSinhVien;
     private String email;
     private String diaChi;
     //
     private Set<KhoaHoc> khoahocs = new HashSet<KhoaHoc>(0);

    public Set<KhoaHoc> getKhoahocs() {
        return khoahocs;
    }

    public void setKhoahocs(Set<KhoaHoc> khoahocs) {
        this.khoahocs = khoahocs;
    }
     
    public SinhVien() {
    }

	
    public SinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public SinhVien(String maSinhVien, String tenSinhVien, String email, String diaChi) {
       this.maSinhVien = maSinhVien;
       this.tenSinhVien = tenSinhVien;
       this.email = email;
       this.diaChi = diaChi;
    }
   
    public String getMaSinhVien() {
        return this.maSinhVien;
    }
    
    public void setMaSinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public String getTenSinhVien() {
        return this.tenSinhVien;
    }
    
    public void setTenSinhVien(String tenSinhVien) {
        this.tenSinhVien = tenSinhVien;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }




}


