/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernateweek5;

import dao.MonHocDAO;
import static hibernateweek5.FormCheckSv.tenMon;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import pojo.*;

/**
 *
 * @author admin1
 */
public class FormGiaoVu extends javax.swing.JFrame {

    Date ngayBd;
    Date ngayKt;
    Date gioBd;
    Date gioKt;
    public FormGiaoVu() {
      try{
            // Làm đẹp giao diện
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}
        catch(Exception e){};
       
        initComponents();
         setLocationRelativeTo(null); //dat duoi ms apply dk
         Date date = new Date();
        
          SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        String strDate = formatter.format(date);
        //System.out.println("Date Format with MM/dd/yyyy: " + strDate);
        ngaybd.setText(strDate);
        //xử lý ngày
//       StringTokenizer st = new StringTokenizer(strDate, "/");
//       String[] s = new String[3];
//       int i = 0;
//        while (st.hasMoreTokens()) {
//           //System.out.println(st.nextToken());
//           s[i] = st.nextToken();
//            //System.out.println(s[i] );
//          i++;
//        }
//
//            int k = Integer.parseInt(s[0]);
//            k++;
//            String thang = String.valueOf(k);
//            if(thang.length() == 1){
//                thang = "0" + thang;
//            }
//            ngaykt.setText(thang + "/" + s[1] + "/" + s[2]);

            

            ///***********************************************
        formatter = new SimpleDateFormat("hh:mm");
        strDate = formatter.format(date);
        //System.out.println("Date Format : " + strDate);
        giobd.setText(strDate);
        //xu lý gio
        StringTokenizer st1 = new StringTokenizer(strDate, ":");
       String[] s1 = new String[3];
       int i1 = 0;
        while (st1.hasMoreTokens()) {
           //System.out.println(st.nextToken());
           s1[i1] = st1.nextToken();
            //System.out.println(s[i] );
          i1++;
        }

            int k1 = Integer.parseInt(s1[0]);
            k1 = k1 + 4;
            giokt.setText(String.valueOf(k1) + ":" + s1[1]);
            //System.out.println("gio kt: " + giokt.getText());
        formatter = new SimpleDateFormat("MM/dd/yyyy hh:mm");//"MM-dd-yyyy hh:mm"
        //strDate = formatter.format(date);
        //strDate = ngaybd.getText() + " "+ giobd.getText();
        //System.out.println(strDate);
         try {
            //Date date1 = formatter.parse("02:02");
            gioBd = formatter.parse(ngaybd.getText() + " "+ giobd.getText());
            System.out.println("gio bat dau: " + gioBd);
             gioKt = formatter.parse(ngaybd.getText() + " "+ giokt.getText());
            System.out.println("gio ket thuc: " + gioKt);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ngaybd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ngaykt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        giobd = new javax.swing.JTextField();
        giokt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        thu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phong = new javax.swing.JTextField();
        AddSubject = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MaMon = new javax.swing.JTextField();
        TenMon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        addCheck = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giáo Vụ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời khóa biểu"));

        jLabel3.setText("Ngày bắt đầu");

        jLabel4.setText("Ngày kết thúc");

        jLabel5.setText("Khoảng thời gian");

        jTextField5.setText("15 tuần");

        jLabel6.setText("Giờ bắt đầu");

        jLabel7.setText("Giờ kết thúc");

        jLabel8.setText("Thứ trong tuần");

        thu.setText("2");

        jLabel9.setText("Phòng học");

        phong.setText("C11");

        AddSubject.setText("Tạo môn học");
        AddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ngaykt, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(ngaybd)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(giobd)
                            .addComponent(giokt)
                            .addComponent(thu)
                            .addComponent(phong))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddSubject)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(giobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(giokt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(thu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(AddSubject))
        );

        jLabel1.setText("Mã môn:");

        jLabel2.setText("Tên môn:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(MaMon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton2.setText("Xem kết quả điểm danh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addCheck.setText("Thêm danh sách sinh viền bằng cách check");
        addCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCheckActionPerformed(evt);
            }
        });

        jButton4.setText("Đăng xuất");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        CSV.setText("Thêm danh sách bằng cách nhập hay csv   ");
        CSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(addCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CSV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FormLogin f = new FormLogin();
        f.setVisible(true);
        setVisible(false);
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubjectActionPerformed
        if(MaMon.getText().equals("")!= true && TenMon.getText().equals("") != true) {
        MonHoc mh = new MonHoc(); 
            mh.setMaMonHoc(MaMon.getText());
            mh.setTenMonHoc(TenMon.getText());
            ThoiKhoaBieu tkb = new ThoiKhoaBieu();
            tkb.setMaTkb(MaMon.getText());//ma tkb la ma mon hoc
            tkb.setTenPhongHoc(phong.getText());
            tkb.setKhoangThoiGian(15);
            tkb.setThu(Integer.parseInt(thu.getText()));
            
                SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy hh:mm");//"MM-dd-yyyy hh:mm"

                try {
                   //Date date1 = formatter.parse("02:02");
                   gioBd = formatter.parse(ngaybd.getText() + " "+ giobd.getText());
                   System.out.println("gio bat dau: " + gioBd);
                    gioKt = formatter.parse(ngaybd.getText() + " "+ giokt.getText());
                   System.out.println("gio ket thuc: " + gioKt);
               } catch (ParseException e) {
                   e.printStackTrace();
               }   
                   formatter = new SimpleDateFormat("MM/dd/yyyy");//"MM-dd-yyyy hh:mm"

                try {
                   ngayBd = formatter.parse(ngaybd.getText());
                   System.out.println("ngay bat dau: " + gioBd);
                    ngayKt = formatter.parse(ngaykt.getText());
                   System.out.println("ngay ket thuc: " + gioKt);
               } catch (ParseException e) {
                   e.printStackTrace();
               }   
            tkb.setGioBatDau(gioBd);
            tkb.setGioKetThuc(gioKt);
            tkb.setNgayBatDau(ngayBd);
            tkb.setNgayKetThuc(ngayKt);

            mh.setThoiKhoaBieu(tkb);
            boolean kq1 = MonHocDAO.themMonHoc(mh);
            if(kq1 == true){
                System.out.println(" Thêm thành công");
                JOptionPane.showMessageDialog(null, " Thêm thành công");
            }
            else{
                System.out.println("Thêm thất bại");
                JOptionPane.showMessageDialog(null, " Thêm thất bại. Mời bạn nhập lại mã môn học");
            }
        }else{
            JOptionPane.showMessageDialog(null, " Mời bạn nhập lại đầy đủ thông tin môn học");
        }
    }//GEN-LAST:event_AddSubjectActionPerformed

    private void addCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCheckActionPerformed
        String[] a = null;
        FormCheckSv.main(a);
    }//GEN-LAST:event_addCheckActionPerformed

    private void CSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVActionPerformed
        FormAddSinhVien f = new FormAddSinhVien();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_CSVActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String[] a = null;
        FormDiemDanh.main(a);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGiaoVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSubject;
    private javax.swing.JButton CSV;
    private javax.swing.JTextField MaMon;
    private javax.swing.JTextField TenMon;
    private javax.swing.JButton addCheck;
    private javax.swing.JTextField giobd;
    private javax.swing.JTextField giokt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField ngaybd;
    private javax.swing.JTextField ngaykt;
    private javax.swing.JTextField phong;
    private javax.swing.JTextField thu;
    // End of variables declaration//GEN-END:variables
}
