/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernateweek5;

import dao.MonHocDAO;
import dao.SinhVienDAO;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import pojo.MonHoc;
import pojo.SinhVien;
import pojo.SvAccount;

/**
 *
 * @author admin1
 */
public class FormAddSinhVien extends javax.swing.JFrame {

    String fileName;
    public FormAddSinhVien() {
        try{
            // Làm đẹp giao diện
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}
        catch(Exception e){};
       
        initComponents();
         setLocationRelativeTo(null); //dat duoi ms apply dk
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        masv = new javax.swing.JTextField();
        tensv = new javax.swing.JTextField();
        CSV = new javax.swing.JButton();
        AddSV = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        monhoc = new javax.swing.JTextField();
        Thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm sinh viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm sinh viên"));

        jLabel1.setText("Mã sinh viên: ");

        jLabel2.setText("Tên sinh viên:");

        CSV.setText("Import file csv để thêm sinh viên");
        CSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVActionPerformed(evt);
            }
        });

        AddSV.setText("Thêm sinh viên vào môn học");
        AddSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSVActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã môn học: ");

        Thoat.setText("Thoát");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(masv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tensv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(monhoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Thoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(monhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(AddSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Thoat))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSVActionPerformed
        if(masv.getText().equals("") != true && tensv.getText().equals("") != true && monhoc.getText().equals("") != true){
            SinhVien sv1=new SinhVien(); 
            sv1.setMaSinhVien(masv.getText().trim());
            sv1.setHoTen(tensv.getText().trim());
            SvAccount acc =new SvAccount();
            acc.setIdsvaccount(masv.getText().trim());
            acc.setUsername(masv.getText().trim());
            acc.setPassword(masv.getText().trim());
            
           
            sv1.setIdsvaccount(acc);
            //thêm và sửa mon hoc
            MonHoc v=null;
            v=MonHocDAO.layThongTinMonHoc(monhoc.getText().trim());
            boolean kq1 = false;
            

        //neu co mon hoc
        if(v != null){
            //neu co mon hoc r ms dk them
            kq1  = SinhVienDAO.themSinhVien(sv1);
            if(v.getMaSinhVien() == null){
                 v.setMaSinhVien(masv.getText().trim()); //thêm từng sv vào
            }else{
                //neu mon hoc co sinh vien roi
                String listSv =  v.getMaSinhVien();
                listSv =  listSv.trim() + " " + masv.getText().trim();
                v.setMaSinhVien(listSv);
            }
        }
             //  System.out.println(v.getTenMonHoc());
            //neu them sv moi thanh cong moi dk nhap mon moi va mon hoc do phai ton tai roi
            boolean kq2 = false;
            if(kq1 == true && v != null){
                kq2 = MonHocDAO.updateMonHoc(v);
                
                //System.out.println(" Thêm thành công");
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            }
            else{
                String mess = "";
                if(v == null){
                   mess = mess + "Môn học không tại! Mời bạn nhập lại thông tin";
                }else{
                    //neu có môn hoc mà thêm sv thất bại có nghĩa là mssv đã tồn tại
                    if(kq1 == false){
                        mess = "Sinh viên đã tồn tại rồi. " + mess;
                    }
                }
                if(kq1 == false)
                JOptionPane.showMessageDialog(null, "Thêm thất bại sinh viên có mã SV là: " + masv.getText() + "! " + mess+" Mời bạn nhập lại thông tin!" );
            }
           }else{
               JOptionPane.showMessageDialog(null, "Bạn phải nhập đầy đủ thông tin");
           }
    }//GEN-LAST:event_AddSVActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FormGiaoVu f = new FormGiaoVu();
        f.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void CSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =  chooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        //System.out.println(fileName);
        String s = readLineFile();
//        if(s.equals("") == true){
//            JOptionPane.showMessageDialog(null, "Thêm thành công");
//        }else{
//            JOptionPane.showMessageDialog(null, "Các sinh viên thêm lỗi là: " + s);
//        }
    }//GEN-LAST:event_CSVActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
      
        setVisible(false);
    }//GEN-LAST:event_ThoatActionPerformed
    //ham doc file csv
        public String readLineFile() {
      
            String themLoi = ""; 
        try (FileReader f = new FileReader(fileName); BufferedReader b = new BufferedReader(f)) {
                String line = null;
                System.out.println("=====");
                while((line = b.readLine())!= null){

                      String[] str1 = line.split(",");
                      for(int i = 0; i < str1.length; i++){
                          System.out.println(str1[i]);
                      }
                        //thêm sv vao mon hoc
                        //String s = addSinhVien("9", "9", "VL");
                       String s = addSinhVien(str1[0].trim(), str1[1].trim(), str1[2].trim());
                       if(s.equals("") != true){
                           themLoi = themLoi + s + " ";
                       }
            }
                b.close();
                f.close();
        } catch (FileNotFoundException ex) {
            System.out.println("open file error: file not found");
        } catch (IOException ex) {
             System.out.println("open file error");
        }
        
        return themLoi;
    }
        
     //hàm add sv trả về sv lỗi khi thêm
     public String addSinhVien(String maSinhVien, String tenSinhVien, String maMonHoc){
         String s = "";
         SinhVien sv1=new SinhVien(); 
            sv1.setMaSinhVien(maSinhVien);
            sv1.setHoTen(tenSinhVien);
            SvAccount acc =new SvAccount();
            acc.setIdsvaccount(maSinhVien);
            acc.setUsername(maSinhVien);
            acc.setPassword(maSinhVien);
            
           
            sv1.setIdsvaccount(acc);
            //thêm và sửa mon hoc
            MonHoc v=null;
            v=MonHocDAO.layThongTinMonHoc(maMonHoc);
            boolean kq1 = false;
            

        //neu co mon hoc
        if(v != null){
            //neu co mon hoc r ms dk them
            kq1  = SinhVienDAO.themSinhVien(sv1);
            if(v.getMaSinhVien() == null){
                 v.setMaSinhVien(maSinhVien); //thêm từng sv vào
            }else{
                //neu mon hoc co sinh vien roi
                String listSv =  v.getMaSinhVien();
                
                listSv =  listSv.trim() + " " + maSinhVien.trim();
                  
                v.setMaSinhVien(listSv);
            }
        }
            
            //neu them sv moi thanh cong moi dk nhap mon moi va mon hoc do phai ton tai roi
            boolean kq2 = false;
            if(kq1 == true && v != null){
                kq2 = MonHocDAO.updateMonHoc(v);
                //JOptionPane.showMessageDialog(null, "Thêm thành công");
            }
            else{
                s = maSinhVien;
            }
           
         return s;
         
     }
     
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSV;
    private javax.swing.JButton CSV;
    private javax.swing.JButton Thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField masv;
    private javax.swing.JTextField monhoc;
    private javax.swing.JTextField tensv;
    // End of variables declaration//GEN-END:variables
}
