/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernateweek5;

import javax.swing.UIManager;
import dao.DiemDanhDAO;
import dao.MonHocDAO;
import dao.SinhVienDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import pojo.DiemDanh;
import pojo.MonHoc;
import pojo.SinhVien;
import pojo.SvAccount;

public class FormSinhVien1 extends javax.swing.JFrame {

    /**
     * Creates new form FormSinhVien
     */
    static String maMon0;
    static String maSinhVien0;
    public FormSinhVien1() {
      try{
            // Làm đẹp giao diện
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}
        catch(Exception e){};
       
        initComponents();
         setLocationRelativeTo(null); //dat duoi ms apply dk
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maMon = new javax.swing.JTextField();
        thu1 = new javax.swing.JTextField();
        gio = new javax.swing.JTextField();
        ngayHoc = new javax.swing.JTextField();
        maSV = new javax.swing.JTextField();
        diemDanh = new javax.swing.JButton();
        changePass = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        XemKq = new javax.swing.JButton();
        thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điểm danh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 255, 204))); // NOI18N

        jLabel1.setText("Mã môn:");

        jLabel2.setText("Thứ:");

        jLabel3.setText("Giờ học:");

        jLabel4.setText("Ngày học(MM/dd/YYYY): ");

        jLabel5.setText("Mã sinh viên:");

        thu1.setText("2");

        gio.setText("6:50");

        ngayHoc.setText("04/07/2018");

        diemDanh.setText("Điểm danh");
        diemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemDanhActionPerformed(evt);
            }
        });

        changePass.setText("Đổi mật khẩu");
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(diemDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePass))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(maMon, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thu1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(gio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ngayHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(maSV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(thu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(gio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ngayHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diemDanh)
                    .addComponent(changePass))
                .addGap(42, 42, 42))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xem kết quả điểm danh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 255, 204))); // NOI18N

        XemKq.setText("Xem kết quả điểm danh");
        XemKq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XemKqActionPerformed(evt);
            }
        });

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(XemKq)
                .addGap(96, 96, 96)
                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XemKq)
                    .addComponent(thoat))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XemKqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XemKqActionPerformed
        maMon0 = maMon.getText().toUpperCase();
          maSinhVien0 = maSV.getText();
        if(maMon.getText().equals("") == false && maSV.getText().equals("") == false){
        String[] a = null;
        FormKQDiemDanhSV.main(a);
       }else{
           JOptionPane.showMessageDialog(null, "Bạn phải điền đầy đủ thông tin");
   }
    }//GEN-LAST:event_XemKqActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        FormLogin f = new FormLogin();
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_thoatActionPerformed

    private void diemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemDanhActionPerformed
       boolean kiemtra = true;  
        String tuanDiHoc = "";
        if(maMon.getText().equals("") == true || maSV.getText().equals("") == true){
            JOptionPane.showMessageDialog(null, "Bạn phải nhập đầy đủ thông tin");
        }else{
        //kiem tra ma mon hop le
        MonHoc v = null;
         
        v = MonHocDAO.layThongTinMonHoc(maMon.getText().toUpperCase());
          
        //neu co mon hoc
        if(v != null){
            System.out.println(v.getTenMonHoc());
            Date d1 = new Date(v.getThoiKhoaBieu().getNgayBatDau().getTime());
            System.out.println("Date bd: " + d1); //2018-04-07
            Date d2 = new Date(v.getThoiKhoaBieu().getNgayKetThuc().getTime());
            System.out.println("Date kt: " + d2); //2018-07-15
            
            Date gioBd = new Date(v.getThoiKhoaBieu().getGioBatDau().getTime());
            System.out.println("time bd: " + gioBd); //2018-04-07
            Date gioKt = new Date(v.getThoiKhoaBieu().getGioKetThuc().getTime());
            System.out.println("time kt: " + gioKt); //2018-04-07
           
                
                SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy hh:mm");
              
                Date date2 = new Date();
                
                try {
                    date2 = formatter.parse("01-01-1970 " + gio.getText());
                    System.out.println("gio hoc: " + date2);
                     String strDate = formatter.format(date2);
                System.out.println("Date Format with dd-MM-yyyy hh:mm: " + strDate);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
               
                //neu dk nằm trong giờ điểm danh thì ok
                if(date2.getTime() >= gioBd.getTime() && date2.getTime() <= gioKt.getTime()){
                    System.out.println("Thời gian điểm danh hợp lệ");
                }else{
                    kiemtra = false;
                    System.out.println("Giờ điểm danh không hợp lệ");
                    JOptionPane.showMessageDialog(null, "Giờ điểm danh không hợp lệ");
                }
               // System.out.println("thứ " + Integer.parseInt(thu.getText()));
               //System.out.println("thứ: " + thu1.getText());
              //  System.out.println("thứ " + v.getThoiKhoaBieu().getThu
              if(thu1.getText().equals("") == false){
                if (Integer.parseInt(thu1.getText()) == v.getThoiKhoaBieu().getThu()) {
                    System.out.println("Thứ hợp lệ");
                } else {
                    kiemtra = false;
                    System.out.println("Thứ không hợp lệ");
                    JOptionPane.showMessageDialog(null, "Thứ không hợp lệ");
                   }
              }
              //tinh thoi gian ra tuan thu may
               //tính toán 1 tuần
                long  thoiGianMotTuan = 0L;
                long  thoiGian15Tuan = 0L;
                 formatter = new SimpleDateFormat("MM/dd/yyyy");
                try {
                    Date date4 = formatter.parse("04/07/2018");
                    //System.out.println("Date1: " + date4);
                    Date date5 = formatter.parse("04/14/2018");
                    //System.out.println("Date2: " + date5);
                    thoiGianMotTuan = date5.getTime() - date4.getTime();
                    thoiGian15Tuan = thoiGianMotTuan*15;
                    
                    Date date6 = formatter.parse(ngayHoc.getText());
                    System.out.println("ngay hoc: " + date6);
                   //tinh toán
                   if(date6.getTime() >= d1.getTime() && date6.getTime() <= d2.getTime()){
                        int tuan = (int) ((date6.getTime() - d1.getTime())/thoiGianMotTuan) + 1; //công thêm 1 vì tuần đầu chia ra nó sẽ là 0
                        if(tuan >= 16){
                            tuan = 15;
                        }
                        tuanDiHoc = String.valueOf(tuan);
                   }else{
                       kiemtra = false;
                       JOptionPane.showMessageDialog(null, "Ngày điểm danh không hợp lệ");
                   }
                   // System.out.println("tuan thu: " + tuan );
                    
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                //nếu sv nằm trong môn đó
               if(v.getMaSinhVien().contains(maSV.getText()) == false){
                   kiemtra = false;
                    JOptionPane.showMessageDialog(null, "Mã sv không hợp lệ, sv chưa đăng kí học môn đó");
               }
        }else{
            kiemtra = false;
            JOptionPane.showMessageDialog(null, "Mã môn không hợp lệ");
        }
        
        //neu TM cả 3 dk
         if(kiemtra == true){
                 List<DiemDanh> ds3 = DiemDanhDAO.layDanhSachDiemDanh(maSV.getText(), v.getMaMonHoc());
                 //neu tim trong bang diem danh có sv r thi cap nhat lai tuan di hoc con neu k co thì them
                if(ds3.toString().equals("[]") == false){
                   // System.out.println(ds.size());
                 for(int i3=0; i3<ds3.size(); i3++){
                  DiemDanh sv3=ds3.get(i3);
                  System.out.println("========diem danh=======");
                     System.out.println("Mã: " + sv3.getMaSinhVien());
                    System.out.println("Tuần: " + sv3.getTuan());
                    //neu tuan do diem danh roi thi k co diem danh nua
                     System.out.println("tuan di hoc: " + tuanDiHoc);

                    if(sv3.getTuan().contains(tuanDiHoc.trim()) == false){
                        tuanDiHoc = tuanDiHoc.trim() + " " + sv3.getTuan().trim();
                        sv3.setTuan(tuanDiHoc.trim());// update
                    }
                    MonHoc c3 = sv3.getMaMonHoc();
                     System.out.println("tên môn: " + c3.getTenMonHoc());
                    //cap nhat lai tuan di hoc cho sv
                    boolean kq1 = DiemDanhDAO.updateDiemDanh(sv3);
                   if(kq1 == true){
                            System.out.println(" SV điểm danh thành công");
                            JOptionPane.showMessageDialog(null, "SV điểm danh thành công");
                    }else{
                           System.out.println(" SV điểm danh thất bại");
                           JOptionPane.showMessageDialog(null, "SV điểm danh thất bại");
                     }

                 }
                }else{
                    v.setMaMonHoc(v.getMaMonHoc().toUpperCase());
                    DiemDanh f = DiemDanhDAO.addDiemDanh(maSV.getText(), v, tuanDiHoc);
                   if(f != null){
                            System.out.println(" thêm thành công");
                            JOptionPane.showMessageDialog(null, "SV điểm danh thành công");
                    }else{
                           System.out.println(" thêm thất bại");
                           JOptionPane.showMessageDialog(null, "SV điểm danh thất bại");
                     }
                    System.out.println("error");
                }
         }
        }
    }//GEN-LAST:event_diemDanhActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
        if(maSV.getText().equals("") == false)  {
        String pass = JOptionPane.showInputDialog("Mời bạn nhập mật khẩu mới!");
            
            SinhVien sv1=new SinhVien(); 
            sv1.setMaSinhVien(maSV.getText());
            SinhVien v=null;
            v=SinhVienDAO.layThongTinSinhVien(maSV.getText());
            if(v != null){
              
                sv1.setHoTen(v.getHoTen());
                SvAccount acc =new SvAccount();
                acc.setIdsvaccount(maSV.getText());
                acc.setUsername(maSV.getText());
                acc.setPassword(pass);
                 sv1.setIdsvaccount(acc);
            }
           
           
            boolean kq1 =SinhVienDAO.updateSinhVien(sv1);
            if(kq1 == true){
                System.out.println(" Sửa thành công");
                JOptionPane.showMessageDialog(null, "Sửa mật khẩu thành công");
            }
            else{
               JOptionPane.showMessageDialog(null,"Sửa mật khẩu thất bại");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Bạn phải nhập đầy đủ thông tin");
        }
           
           
            
            

    }//GEN-LAST:event_changePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSinhVien1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XemKq;
    private javax.swing.JButton changePass;
    private javax.swing.JButton diemDanh;
    private javax.swing.JTextField gio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField maMon;
    private javax.swing.JTextField maSV;
    private javax.swing.JTextField ngayHoc;
    private javax.swing.JButton thoat;
    private javax.swing.JTextField thu1;
    // End of variables declaration//GEN-END:variables
}
