package hibernate;
// Generated Apr 2, 2018 10:09:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer id;
     private String streetName;
     private String cityName;
     private String stateName;
     private String zipcode;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Address() {
    }
    public Address(String street, String city, String state, String zipcode) {
        this.streetName = street;
        this.cityName = city;
        this.stateName = state;
        this.zipcode = zipcode;
    }
//    public Address(String streetName, String cityName, String stateName, String zipcode, Set<Employee> employees) {
//       this.streetName = streetName;
//       this.cityName = cityName;
//       this.stateName = stateName;
//       this.zipcode = zipcode;
//       this.employees = employees;
//    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


