package pojo;
// Generated Apr 4, 2018 9:25:36 AM by Hibernate Tools 4.3.1



/**
 * Giaovu generated by hbm2java
 */
public class GiaoVu  implements java.io.Serializable {


     private String maGiaoVu;
     private String hoTen;
     private GvAccount idgvaccount;
     private String maMonHoc;

    public GiaoVu() {
    }

	
    public GiaoVu(String maGiaoVu) {
        this.maGiaoVu = maGiaoVu;
    }
    public GiaoVu(String maGiaoVu, String hoTen, GvAccount idgvaccount, String maMonHoc) {
       this.maGiaoVu = maGiaoVu;
       this.hoTen = hoTen;
       this.idgvaccount = idgvaccount;
       this.maMonHoc = maMonHoc;
    }
   
    public String getMaGiaoVu() {
        return this.maGiaoVu;
    }
    
    public void setMaGiaoVu(String maGiaoVu) {
        this.maGiaoVu = maGiaoVu;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public GvAccount getIdgvaccount() {
        return this.idgvaccount;
    }
    
    public void setIdgvaccount(GvAccount idgvaccount) {
        this.idgvaccount = idgvaccount;
    }
    public String getMaMonHoc() {
        return this.maMonHoc;
    }
    
    public void setMaMonHoc(String maMonHoc) {
        this.maMonHoc = maMonHoc;
    }




}


